//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int MealId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public int Lunch { get; set; }
        public int Dinnar { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
