//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string StudentName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string MobileNumber { get; set; }
    
        public virtual DepartmentInfo DepartmentInfo { get; set; }
        public virtual Room Room { get; set; }
        public virtual Users Users { get; set; }
        public virtual Preference Preference { get; set; }
        public virtual Address Address { get; set; }
    }
}
